"""
NOVARYX - Deployment Config Generator
Generates configs for Vercel, Railway, Netlify, and GitHub Actions CI/CD.
"""

import json
import logging
from typing import Dict, Optional

logger = logging.getLogger("novaryx.deploy_configs")


class DeployConfigGenerator:
    """Generates deployment configurations for multiple platforms"""
    
    @staticmethod
    def generate_vercel_config(project_name: str) -> str:
        """Generate vercel.json"""
        slug = project_name.lower().replace(" ", "-")
        
        config = {
            "name": slug,
            "version": 2,
            "builds": [
                {
                    "src": "package.json",
                    "use": "@vercel/static-build",
                    "config": {
                        "distDir": "dist"
                    }
                }
            ],
            "routes": [
                {
                    "src": "/(.*)",
                    "dest": "/index.html"
                }
            ],
            "env": {
                "VITE_APP_NAME": project_name,
                "VITE_APP_VERSION": "1.0.0"
            }
        }
        
        return json.dumps(config, indent=2)
    
    @staticmethod
    def generate_railway_config(project_name: str) -> str:
        """Generate railway.toml / railway.json"""
        slug = project_name.lower().replace(" ", "-")
        
        config = {
            "$schema": "https://railway.app/railway.schema.json",
            "build": {
                "builder": "NIXPACKS",
                "buildCommand": "npm run build"
            },
            "deploy": {
                "startCommand": "npm run preview -- --port $PORT --host 0.0.0.0",
                "restartPolicyType": "ON_FAILURE",
                "numReplicas": 1
            }
        }
        
        return json.dumps(config, indent=2)
    
    @staticmethod
    def generate_netlify_config(project_name: str) -> str:
        """Generate netlify.toml"""
        slug = project_name.lower().replace(" ", "-")
        
        return f"""# {project_name} - Netlify Configuration
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
"""
    
    @staticmethod
    def generate_github_actions(project_name: str) -> str:
        """Generate GitHub Actions CI/CD workflow"""
        slug = project_name.lower().replace(" ", "-")
        
        return f"""# {project_name} - CI/CD Pipeline
# Generated by NOVARYX

name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npx tsc --noEmit
      
      - name: Build
        run: npm run build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

  deploy-vercel:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{{{ secrets.VERCEL_TOKEN }}}}
          vercel-org-id: ${{{{ secrets.VERCEL_ORG_ID }}}}
          vercel-project-id: ${{{{ secrets.VERCEL_PROJECT_ID }}}}
          vercel-args: '--prod'
"""
    
    @staticmethod
    def generate_all_configs(project_name: str, has_backend: bool = False) -> Dict[str, str]:
        """Generate all deployment configs"""
        configs = {
            "vercel.json": DeployConfigGenerator.generate_vercel_config(project_name),
            "railway.json": DeployConfigGenerator.generate_railway_config(project_name),
            "netlify.toml": DeployConfigGenerator.generate_netlify_config(project_name),
            ".github/workflows/deploy.yml": DeployConfigGenerator.generate_github_actions(project_name),
        }
        
        return configs