"""
NOVARYX - Docker Packager
Generates Docker configurations for containerized deployment.
"""

import logging
from typing import Dict, Optional
from datetime import datetime

logger = logging.getLogger("novaryx.docker_packager")


class DockerPackager:
    """Generates Docker files for project deployment"""
    
    @staticmethod
    def generate_dockerfile(project_name: str, has_backend: bool = False, node_version: str = "20") -> str:
        """Generate production Dockerfile"""
        
        return f"""# {project_name} - Dockerfile
# Generated by NOVARYX

FROM node:{node_version}-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy source
COPY . .

# Build
RUN npm run build

# Production stage
FROM node:{node_version}-alpine AS production

WORKDIR /app

# Install serve for static files
RUN npm install -g serve

# Copy built files
COPY --from=builder /app/dist ./dist

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

# Run
CMD ["serve", "-s", "dist", "-l", "3000"]
"""
    
    @staticmethod
    def generate_docker_compose(
        project_name: str,
        has_backend: bool = False,
        frontend_port: int = 3000,
        backend_port: int = 8090
    ) -> str:
        """Generate docker-compose.yml"""
        
        slug = project_name.lower().replace(" ", "-")
        
        compose = f"""# {project_name} - Docker Compose
# Generated by NOVARYX

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {slug}-frontend
    restart: unless-stopped
    ports:
      - "{frontend_port}:3000"
    environment:
      - NODE_ENV=production
"""
        
        if has_backend:
            compose += f"""
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: {slug}-backend
    restart: unless-stopped
    ports:
      - "{backend_port}:8090"
    volumes:
      - ./backend/pb_data:/pb_data
      - ./backend/pb_migrations:/pb_migrations
    environment:
      - PB_ENCRYPTION_KEY=${{PB_ENCRYPTION_KEY}}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  frontend:
    environment:
      - VITE_POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy
"""
        
        compose += f"""
networks:
  default:
    name: {slug}-network
"""
        
        return compose
    
    @staticmethod
    def generate_dockerignore() -> str:
        """Generate .dockerignore"""
        return """node_modules
.git
.gitignore
*.md
.env
.env.local
.env.production
logs
*.log
tmp
temp
.cache
dist
.novaryx*
"""
    
    @staticmethod
    def generate_deploy_script(project_name: str) -> str:
        """Generate deploy.sh for quick Docker deployment"""
        slug = project_name.lower().replace(" ", "-")
        
        return f"""#!/bin/bash
# {project_name} - Quick Deploy Script
# Generated by NOVARYX

set -e

echo "🚀 Deploying {project_name}..."

# Build
echo "📦 Building Docker image..."
docker build -t {slug}:latest .

# Stop existing container
if docker ps -a | grep -q {slug}-frontend; then
    echo "🛑 Stopping existing container..."
    docker stop {slug}-frontend || true
    docker rm {slug}-frontend || true
fi

# Run
echo "▶️  Starting container..."
docker run -d \\
    --name {slug}-frontend \\
    --restart unless-stopped \\
    -p 3000:3000 \\
    {slug}:latest

# Health check
echo "🔍 Checking health..."
sleep 5
if curl -s http://localhost:3000 > /dev/null; then
    echo "✅ {project_name} is running at http://localhost:3000"
else
    echo "⚠️  Container started but health check failed"
    docker logs {slug}-frontend --tail 20
fi
"""