"""
NOVARYX - Run Script Generator
Generates one-click run scripts for all platforms.
"""

import logging
from typing import Dict

logger = logging.getLogger("novaryx.run_scripts")


class RunScriptGenerator:
    """Generates platform-specific run scripts"""
    
    @staticmethod
    def generate_windows_script(project_name: str) -> str:
        """Generate run.bat for Windows"""
        return f"""@echo off
REM {project_name} - Quick Start Script (Windows)
REM Generated by NOVARYX

echo ========================================
echo   {project_name}
echo   Starting development server...
echo ========================================
echo.

cd /d "%~dp0"

echo [1/2] Installing dependencies...
call npm install

echo.
echo [2/2] Starting dev server...
call npm run dev

pause
"""
    
    @staticmethod
    def generate_unix_script(project_name: str) -> str:
        """Generate run.sh for Linux/Mac"""
        return f"""#!/bin/bash
# {project_name} - Quick Start Script (Linux/Mac)
# Generated by NOVARYX

set -e

echo "========================================"
echo "  {project_name}"
echo "  Starting development server..."
echo "========================================"
echo ""

cd "$(dirname "$0")"

echo "[1/2] Installing dependencies..."
npm install

echo ""
echo "[2/2] Starting dev server..."
npm run dev
"""
    
    @staticmethod
    def generate_setup_guide(project_name: str, has_backend: bool = False) -> str:
        """Generate SETUP.md with detailed instructions"""
        
        slug = project_name.lower().replace(" ", "-")
        
        guide = f"""# {project_name} - Setup Guide

Generated by **NOVARYX** - AI-Powered Application Builder

## Quick Start

### Windows
```cmd
run.bat
```

### Mac / Linux
```bash
chmod +x run.sh
./run.sh
```

## Manual Setup

### Prerequisites
- Node.js 18+ ([Download](https://nodejs.org/))
- npm (comes with Node.js)
"""

        if has_backend:
            guide += """- PocketBase ([Download](https://pocketbase.io/docs/))

"""

        guide += f"""
### Installation

```bash
# Install frontend dependencies
npm install

# Start development server
npm run dev
```

The app will open at http://localhost:3000

"""

        if has_backend:
            guide += f"""### Backend Setup

```bash
# Download PocketBase
# Extract to backend/ directory

# Start PocketBase
cd backend
./pocketbase serve

# Open Admin UI
# http://localhost:8090/_/
# Create admin account on first visit
```
"""

        guide += f"""
## Project Structure

```text
{slug}/
├── src/
│   ├── components/     # React components
│   ├── layouts/        # Page layouts
│   ├── pages/          # Page components
│   ├── styles/         # CSS and design tokens
│   ├── hooks/          # Custom React hooks
│   ├── types/          # TypeScript types
│   ├── App.tsx         # Main app with routing
│   └── main.tsx        # Entry point
├── public/             # Static assets
├── index.html          # HTML template
├── package.json        # Dependencies
├── tsconfig.json       # TypeScript config
├── tailwind.config.js  # Tailwind CSS config
└── vite.config.js      # Vite config
```
"""

        if has_backend:
            guide += """
├── backend/
│   ├── pb_migrations/  # Database migrations
│   └── pb_schema.json  # Collection schemas
"""

        guide += """
## Available Scripts

| Command | Description |
|---------|-------------|
| `npm run dev` | Start development server |
| `npm run build` | Build for production |
| `npm run preview` | Preview production build |

## Deployment

See deployment configs:
- `vercel.json` - Deploy to Vercel
- `netlify.toml` - Deploy to Netlify
- `railway.json` - Deploy to Railway
- `Dockerfile` - Docker deployment
- `.github/workflows/deploy.yml` - GitHub Actions CI/CD

## Support

Generated by NOVARYX v2.7.0
"""
        
        return guide
    
    @staticmethod
    def generate_all_scripts(project_name: str, has_backend: bool = False) -> Dict[str, str]:
        """Generate all run scripts and guides"""
        return {
            "run.bat": RunScriptGenerator.generate_windows_script(project_name),
            "run.sh": RunScriptGenerator.generate_unix_script(project_name),
            "SETUP.md": RunScriptGenerator.generate_setup_guide(project_name, has_backend),
        }
