"""
NOVARYX - Animation Config Generator
Generates complete animation configuration from prompt + design tokens.
This is the main integration point.
"""

from typing import Dict, Any, Optional
from .animation_registry import AnimationRegistry


class AnimationConfigGenerator:
    """
    Generates complete animation configuration.
    
    Input: User prompt + Design System
    Output: Complete animation configuration for all components
    """
    
    @staticmethod
    def generate(
        prompt: str,
        design_system: Any = None,
        component_list: list = None,
        layout_type: str = "dashboard"
    ) -> Dict[str, Any]:
        """
        Generate complete animation config.
        
        Args:
            prompt: User's project description
            design_system: DesignSystem from Design Token Engine
            component_list: List of component IDs being used
            layout_type: Which layout is active
        
        Returns:
            Complete animation configuration
        """
        
        # Base config from prompt keywords
        config = AnimationRegistry.generate_animation_config(prompt, design_system)
        
        # Add layout-specific defaults
        layout_animations = {
            "dashboard": {
                "page_transition": "fade_slide",
                "scroll_reveal": "fade_up",
            },
            "landing": {
                "page_transition": "fade",
                "scroll_reveal": "fade_up",
            },
            "portfolio": {
                "page_transition": "scale",
                "scroll_reveal": "fade_up",
            },
            "admin": {
                "page_transition": "fade",
                "scroll_reveal": "fade_in",
            },
            "ecommerce": {
                "page_transition": "fade_slide",
                "scroll_reveal": "fade_up",
            },
        }
        
        layout_defaults = layout_animations.get(layout_type, {})
        for key, value in layout_defaults.items():
            if key not in config or not config[key]:
                preset = None
                if key == "page_transition":
                    preset = AnimationRegistry.get_page_transition(value)
                elif key == "scroll_reveal":
                    preset = AnimationRegistry.get_scroll_reveal(value)
                
                if preset:
                    config[key] = {
                        "name": preset.name,
                        "props": preset.to_framer_motion(),
                    }
        
        # Add component-specific animations
        component_animations = {}
        if component_list:
            for comp_id in component_list:
                if comp_id in ["stats_card", "chart_widget"]:
                    component_animations[comp_id] = {
                        "scroll_reveal": "fade_up",
                        "hover": "hover_lift"
                    }
                elif comp_id in ["data_table"]:
                    component_animations[comp_id] = {
                        "scroll_reveal": "fade_in",
                        "hover": "none"
                    }
                elif comp_id in ["sidebar", "navbar"]:
                    component_animations[comp_id] = {
                        "scroll_reveal": "none",
                        "hover": "hover_glow"
                    }
        
        config["component_specific"] = component_animations
        
        # Generate utility code
        config["_generated_imports"] = """
// Animation imports (auto-generated by NOVARYX)
import { PageTransition } from "@/components/animations/PageTransition";
import { ScrollReveal, StaggerContainer, StaggerItem } from "@/components/animations/ScrollReveal";
import { Interactive, Spinner, Skeleton, FadeIn, CountUp } from "@/components/animations/MicroInteractions";
"""
        
        return config
    
    @staticmethod
    def get_animation_imports() -> str:
        """Get all required animation imports"""
        return """
import { motion, AnimatePresence, Variants } from "framer-motion";
"""
    
    @staticmethod
    def get_tailwind_animation_config() -> str:
        """Get Tailwind config for animations"""
        return """
// tailwind.config.js animation extension
module.exports = {
  theme: {
    extend: {
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-up': 'fadeUp 0.6s ease-out',
        'slide-left': 'slideLeft 0.5s ease-out',
        'slide-right': 'slideRight 0.5s ease-out',
        'scale-in': 'scaleIn 0.4s ease-out',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'spin-slow': 'spin 2s linear infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
};
"""


# ---- Test ----

def test_animation_config():
    """Test animation config generation"""
    print("\n" + "=" * 60)
    print("🧪 ANIMATION CONFIG TEST")
    print("=" * 60)
    
    test_prompts = [
        "modern saas dashboard with smooth animations",
        "creative portfolio with dramatic transitions",
    ]
    
    for prompt in test_prompts:
        print(f"\n📝 '{prompt}'")
        config = AnimationConfigGenerator.generate(
            prompt=prompt,
            layout_type="dashboard" if "dashboard" in prompt else "portfolio",
            component_list=["sidebar", "stats_card", "chart_widget", "data_table"]
        )
        
        print(f"   Page: {config['page_transition']['name']}")
        print(f"   Scroll: {config['scroll_reveal']['name']}")
        print(f"   Micro: {config['micro_interaction']['name']}")
        print(f"   Components with custom animations: {list(config['component_specific'].keys())}")
    
    print("\n✅ Animation Config test complete")


if __name__ == "__main__":
    test_animation_config()