"""
NOVARYX - Project Builder
Takes an AssemblyPlan and writes complete project to disk.

Output structure:
  output_project/
  |-- src/
  |   |-- components/
  |   |-- layouts/
  |   |-- pages/
  |   |-- styles/
  |   |-- App.tsx
  |   `-- main.tsx
  |-- public/
  |-- package.json
  |-- tsconfig.json
  |-- tailwind.config.js
  |-- vite.config.js
  `-- index.html
"""

import os
import sys
import json
import shutil
import logging
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from system.templates.dynamic.assembly_engine import AssemblyPlan, AssemblyEngine

logger = logging.getLogger("novaryx.project_builder")


class ProjectBuilder:
    """Builds complete project from AssemblyPlan"""
    
    def __init__(self, output_base_dir: str = None):
        if output_base_dir is None:
            novaryx_root = Path.home() / "novaryx"
            output_base_dir = str(novaryx_root / "projects" / "active")
        
        self.output_base_dir = Path(output_base_dir)
        self.output_base_dir.mkdir(parents=True, exist_ok=True)
    
    def build(self, plan: AssemblyPlan, project_dir_name: str = None) -> str:
        """
        Build complete project from assembly plan.
        
        Args:
            plan: Complete AssemblyPlan
            project_dir_name: Optional directory name (defaults to project name)
        
        Returns:
            Path to built project
        """
        
        # Generate all files
        engine = AssemblyEngine(use_llm=False)
        files = engine.generate_project_files(plan)
        
        # Add required config files not generated by assembly engine
        files["tsconfig.json"] = self._generate_tsconfig()
        files["vite.config.js"] = self._generate_vite_config()
        files["postcss.config.js"] = self._generate_postcss_config()
        files[".env"] = self._generate_env(plan)
        files["README.md"] = self._generate_readme(plan)
        
        # Determine output directory
        dir_name = project_dir_name or plan.project_name.lower().replace(" ", "-")
        output_dir = self.output_base_dir / dir_name
        
        # Clear existing if present
        if output_dir.exists():
            shutil.rmtree(output_dir)
        
        output_dir.mkdir(parents=True)
        
        # Write all files
        print(f"\nBuilding project: {dir_name}")
        print(f"   Location: {output_dir}")
        
        written_count = 0
        for filepath, content in files.items():
            full_path = output_dir / filepath
            full_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)
            
            written_count += 1
            print(f"   [OK] {filepath}")
        
        # Create empty directories that should exist
        for subdir in ["public", "src/pages", "src/hooks", "src/lib"]:
            (output_dir / subdir).mkdir(parents=True, exist_ok=True)
            # Add .gitkeep
            (output_dir / subdir / ".gitkeep").touch()
        
        # Save assembly plan for reference
        plan_path = output_dir / ".novaryx_plan.json"
        with open(plan_path, "w") as f:
            json.dump(plan.to_dict(), f, indent=2)
        
        print(f"\nProject built successfully!")
        print(f"   {written_count} files written")
        print(f"   Location: {output_dir}")
        print(f"\n   To run:")
        print(f"   cd {output_dir}")
        print(f"   npm install")
        print(f"   npm run dev")
        
        return str(output_dir)
    
    def _generate_tsconfig(self) -> str:
        return json.dumps({
            "compilerOptions": {
                "target": "ES2020",
                "lib": ["ES2020", "DOM", "DOM.Iterable"],
                "module": "ESNext",
                "skipLibCheck": True,
                "moduleResolution": "bundler",
                "allowImportingTsExtensions": True,
                "resolveJsonModule": True,
                "isolatedModules": True,
                "noEmit": True,
                "jsx": "react-jsx",
                "strict": True,
                "noUnusedLocals": False,
                "noUnusedParameters": False,
                "noFallthroughCasesInSwitch": True,
                "baseUrl": ".",
                "paths": {
                    "@/*": ["src/*"]
                }
            },
            "include": ["src"]
        }, indent=2)
    
    def _generate_vite_config(self) -> str:
        return """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    open: true,
  },
})
"""
    
    def _generate_postcss_config(self) -> str:
        return """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
"""
    
    def _generate_env(self, plan: AssemblyPlan) -> str:
        return f"""# Environment Variables
# Generated by NOVARYX for: {plan.project_name}
VITE_APP_NAME={plan.project_name}
VITE_APP_VERSION=1.0.0
"""
    
    def _generate_readme(self, plan: AssemblyPlan) -> str:
        return f"""# {plan.project_name}

Generated by **NOVARYX** - AI-Powered Application Builder

## Tech Stack
- React + TypeScript
- Tailwind CSS
- Framer Motion
- {len(plan.components_used)} components
{' - Three.js / React Three Fiber' if plan.components_3d else ''}

## Design System
- Primary Color: {plan.design_system.colors.primary}
- Mode: {plan.design_system.mode}
- Font: {plan.design_system.typography.font_family_primary}
- Glassmorphism: {'Yes' if plan.design_system.effects.glass_enabled else 'No'}
- 3D Features: {'Yes' if plan.components_3d else 'No'}

## Getting Started
```bash
npm install
npm run dev
```

## Project Structure
```
src/
|-- components/     # UI Components
|-- layouts/        # Page Layouts
|-- pages/          # Page Components
|-- styles/         # CSS + Design Tokens
|-- App.tsx         # Main App
`-- main.tsx        # Entry Point
```

## Generated
- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- Prompt: "{plan.prompt[:100]}..."
- Layout: {plan.layout.layout_type.value}
- Components: {len(plan.components_used)}
"""
    
    def build_from_prompt(self, prompt: str, project_name: str = "") -> str:
        """One-shot: prompt -> complete project on disk"""
        
        print("\n" + "=" * 70)
        print("NOVARYX PROJECT BUILDER")
        print("=" * 70)
        print(f"   Prompt: {prompt[:80]}...")
        print("=" * 70)
        
        # Assemble
        engine = AssemblyEngine(use_llm=False)
        plan = engine.assemble(prompt, project_name)
        
        # Build
        output_path = self.build(plan)
        
        return output_path


# ---- Test ----

def test_project_builder():
    """Test the project builder"""
    
    print("\n" + "=" * 70)
    print("PROJECT BUILDER TEST")
    print("=" * 70)
    
    builder = ProjectBuilder()
    
    prompt = "Build a dark purple SaaS dashboard with analytics, stats cards, and a 3D globe"
    
    output_path = builder.build_from_prompt(prompt, "test-dashboard")
    
    print(f"\nProject built at: {output_path}")
    
    return output_path


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s | %(levelname)-7s | %(message)s',
        datefmt='%H:%M:%S'
    )
    test_project_builder()